function createfigure(X1, YMatrix1, X2, Y1)
%CREATEFIGURE1(X1, YMATRIX1, X2, Y1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data
%  X2:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 09-Jan-2019 15:35:10

% Create figure
figure1 = figure();

% Create axes
axes1 = axes('Parent',figure1,'YMinorTick','on','YScale','log',...
    'XMinorTick','on',...
    'XScale','log',...
    'FontSize',17);
%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[2000 10000000]);
box(axes1,'on');
hold(axes1,'on');

% Create multiple lines using matrix input to loglog
loglog1 = loglog(X1,YMatrix1,'LineWidth',2);
set(loglog1(1),'DisplayName','ETAIS-RW','Color',[0 0.447 0.741]);
set(loglog1(2),'DisplayName','RWMH','LineStyle','--',...
    'Color',[0.85 0.325 0.098]);

% Create loglog
loglog(X2,Y1,'ZDataSource','','DisplayName','$\mathcal{O}(1/\sqrt{N})$',...
    'Color',[0.392156862745098 0.392156862745098 0.392156862745098]);

% Create xlabel
xlabel('Number of Samples','FontSize',18.7,'Interpreter','latex');

% Create ylabel
ylabel('$w_{\mbox{error}}$','FontSize',17,'Interpreter','latex');

% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Interpreter','latex','FontSize',15.3,...
    'EdgeColor',[0.15 0.15 0.15]);

